### ISSUE TITLE
await cllient

### ISSUE THREAD

**Issue by mrasin12** [Hardwaregore/SpamMyPhone#1]
i get the error on line 33 
const call = await client.dialPhone({

**Comment by Hardwaregore** [comment]
Did you use an api

**Comment by Hardwaregore** [comment]
Read the readme

**Comment by Hardwaregore** [comment]
Download signal wire using npm

**Comment by mrasin12** [comment]
i did use the api i did everything in the readme file

**Comment by mrasin12** [comment]
and did everything like the tut said i can re try tho

**Comment by Hardwaregore** [comment]
Bruh

**Comment by Hardwaregore** [comment]
Video you running the script.

**Comment by mrasin12** [comment]
aye my bad cuh i aint never use node lmaoo
